FROM	ubuntu:16.04

MAINTAINER alehandru

ENV term=linux

RUN apt-get update && \
    apt-get -y dist-upgrade && \
    apt-get install -qy ca-certificates && \
    apt-get install -qy apt-utils && \
    apt-get update

RUN apt-get -y install vim mc && \
    apt-get -y install iputils-ping curl && \
	apt-get -y update

RUN mkdir -p /opt/snap

ENV PATH "/opt/snap:$PATH"

COPY ./snap /opt/snap

RUN chmod 755 -R /opt/snap

EXPOSE 8181

WORKDIR /opt/snap

ENTRYPOINT ["entrypoint.sh"]

CMD ["snapteld --config config.yaml"]


