#!/bin/bash
ES_HOME=/opt/elasticsearch
ES_MIN_MEM=256m
ES_MAX_MEM=1g
DAEMON=${ES_HOME}/bin/elasticsearch
NAME=elasticsearch
DESC=elasticsearch
PID_FILE=/var/run/${NAME}.pid
LOG_DIR=${ES_HOME}/logs
DATA_DIR=${ES_HOME}/data
WORK_DIR=${ES_HOME}/tmp
CONFIG_FILE=${ES_CONFIG}/config/elasticsearch.yml
DAEMON_OPTS=""
ES_JAVA_OPTS="${ES_JAVA_OPTS} -Des.path.home=$ES_HOME -Des.path.logs=$LOG_DIR -Des.path.data=$DATA_DIR -Des.path.work=$WORK_DIR"
ES_USER=elasticsearch

export ES_JAVA_OPTS

test -x $DAEMON || exit 0

set -e

case "$1" in
  start)
    echo -n "Starting $DESC: "
    mkdir -p $LOG_DIR $DATA_DIR $WORK_DIR
    if start-stop-daemon  --user "${ES_USER}" -c "${ES_USER}" --start --pidfile $PID_FILE --startas $DAEMON -- ${DAEMON_OPTS}
    then
        echo "started."
    else
        echo "failed."
    fi
    ;;
  stop)
    echo -n "Stopping $DESC: "
    if start-stop-daemon --stop --pidfile $PID_FILE
    then
        echo "stopped."
    else
        echo "failed."
    fi
    ;;
  restart|force-reload)
    ${0} stop
    sleep 0.5
    ${0} start
    ;;
  *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop|restart|force-reload}" >&2
    exit 1
    ;;
esac
