control:
  # auto_discover_path sets the directory(s) to auto load plugins and tasks on
  # the start of the snap daemon. This can be a colon separated list of directories.
  auto_discover_path: /opt/snap/plugins:/opt/snap/tasks

  # cache_expiration sets the time interval for the plugin cache to use before
  # expiring collection results from collect plugins. Default value is 500ms
  cache_expiration: 500ms

  # plugin_trust_level sets the plugin trust level for snapteld. The default state
  # for plugin trust level is enabled (1). When enabled, only signed plugins that can
  # be verified will be loaded into snapteld. Signatures are verified from
  # keyring files specified in keyring_path. Plugin trust can be disabled (0) which
  # will allow loading of all plugins whether signed or not. The warning state allows
  # for loading of signed and unsigned plugins. Warning messages will be displayed if
  # an unsigned plugin is loaded. Any signed plugins that cannot be verified will
  # not be loaded. Valid values are 0 - Off, 1 - Enabled, 2 - Warning
  plugin_trust_level: 0

  # temp_dir_path sets the temporary directory which houses the temporary files 
  temp_dir_path: /tmp

  # plugins section contains plugin config settings that will be applied for
  # plugins across tasks.
  # plugins:
  #   publisher:
  #     elasticsearch:
  #       all:
  #         protocol: "http"
  #         address: "grafana"
  #         port: 9200
  #         index: "snap-log"
  #         publish_fields: "Namespace|Config|Data|Timestamp|Unit|Version"

  # tags section contains global tags that will be applied on collected metrics
  # across tasks.
  tags:
    # Tags for all metrics generated by a plugin
    /intel/psutil:
      global_tag_2: global_value_tag_2
    # Tags all metrics
    /:
      global_tag_1: global_value_tag_1
    # Tag for an individual metric
    /intel/psutil/vm/total:
      individual_tag_1: individual_value_tag_1





